### ISSUE TITLE
English Please

### ISSUE THREAD

**Issue by hobolance** [abhat222/Data-Science--Cheat-Sheet#12]
### What is the problem with Chinese README's

Firstly, we congratulate you for getting so much star by sharing this repository with humanity.

But it is very disappointing for non-Chinese speakers when one couldn't understand what a trending repository is about.

When we see such a repo on trending, our minds are blurring like Gollum's.

![Gollum Image](https://media.giphy.com/media/V4uGHRgz0zi6Y/giphy-downsized-large.gif)

There is a way **you can help** to solve this disappointment which I believe is experienced by many people who want to know more about your valuable work and appreciate it.

### What we want:
 - Please add English translation of your README so you are sharing your work and knowledge with more people.

### How this will help you:
 - More feedback to fix and improve your project.
 - New ideas about your project.
 - Greater fame.
 - ![SungerBob Image](https://media.giphy.com/media/3o7absbD7PbTFQa0c8/source.gif)

---

_“Sharing knowledge is the most fundamental act of friendship. Because it is a way you can give something without loosing something.”_

_**— Richard Stallman**_

**Thank you!**	

> The developers of repo will not be held responsible for problems that arise in this script.

> This issue generated by [us/english-please](github.com/us/english-please) script. Please open issue on any error. Thank you!

**Comment by feng3245** [comment]
Don't see any??

**Comment by whyessbee** [comment]
Seeing many 😄

**Comment by Iceblaze9527** [comment]
why I'm Chinese and I don't see a single character of my language, what's happening?

**Comment by feng3245** [comment]
Troll request suspected

**Comment by whyessbee** [comment]
Have patience your problems will be resolved by midnight.

**Comment by 1012598167** [comment]
This is a great project indeed.We can use it to quickly study or reminisce as well, but it's actually hard for Chinese with poor English😭. It will be excellent if it has Chinese verison (just README of the whole project)!

**Comment by rajaranjith** [comment]
> This is a great project indeed.We can use it to quickly study or reminisce as well, but it's actually hard for Chinese with poor English😭. It will be excellent if it has Chinese verison (just README or the whole project better)!

just a small advice, can't we use google translate it to Chinese language?

**Comment by rajaranjith** [comment]
> > This is a great project indeed.We can use it to quickly study or reminisce as well, but it's actually hard for Chinese with poor English😭. It will be excellent if it has Chinese verison (just README or the whole project better)!
> 
> just a small advice, can't we use google translate it to Chinese language?

Done!!!!!

目录
人工智能
大数据分析
大数据
数据工程
数据挖掘
数据科学
数据可视化
深度学习
机器学习
SQL
蟒蛇

**Comment by rajaranjith** [comment]
> > > This is a great project indeed.We can use it to quickly study or reminisce as well, but it's actually hard for Chinese with poor English😭. It will be excellent if it has Chinese verison (just README or the whole project better)!
> > 
> > 
> > just a small advice, can't we use google translate it to Chinese language?
> 
> Done!!!!!
> (Simplified)
> 目录
> 人工智能
> 大数据分析
> 大数据
> 数据工程
> 数据挖掘
> 数据科学
> 数据可视化
> 深度学习
> 机器学习
> SQL
> 蟒蛇

(Traditional)

目錄
人工智能
大數據分析
大數據
數據工程
數據挖掘
數據科學
數據可視化
深度學習
機器學習
SQL
蟒蛇
