### ISSUE TITLE
Shiny Web App cheat sheet

### ISSUE THREAD

**Issue by duniatri** [abhat222/Data-Science--Cheat-Sheet#20]
Hi,
can you also add cheat sheet for Shiny?
here is the link:
https://shiny.rstudio.com/images/shiny-cheatsheet.pdf

**Comment by abhat222** [comment]
Sure thing. Will do it today.

**Comment by abhat222** [comment]
Completed.

Link - https://github.com/abhat222/Data-Science--Cheat-Sheet/blob/master/R%20Cheat%20Sheet/shiny-cheatsheet.pdf
